name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkitout due
        uses: actions/checkout@v2-beta  
      - name: Workspace
        run: ls
      - name: Copy folder content recursively to remote1
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: public_html/admin
          host: ${{ secrets.host }}
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
