name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /index.htm
        remote: scp/public_html/admin
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        password: ${{ secrets.password }}
