name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup demo
      run: |
        mkdir test
        touch test/oof.txt
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: test
        remote: public_html/admin
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        password: ${{ secrets.password }}
