name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Parent working dir
        run: ls ${{ github.repository }}
      - name: Copy folder content recursively to remote1
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ github.repository }}/test
          remote: public_html/admin
          host: ${{ secrets.host }}
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
